### PR TITLE
Do photometry

### PR DESCRIPTION
**Pull request by bsipocz**
preliminary draft of the photometry, with loads of limitations

### CODE REVIEW

**Comment by jradavenport** [comment]
Just saw this!! Will merge asap!

**Comment by bsipocz** [comment]
@jradavenport @hover2pi So, what's the plan to proceed? I saw that you guys started on a different logic, shall we keep that or this to develop further? 

The tricky part will be to use sensible apertures, and standard transformations, etc.

**Comment by bsipocz** [comment]
screen shot 2016-01-08 at 21 13 19

**Comment by hover2pi** [comment]
Brigitta,

I sort of manually merged our modules since they do basically the same thing. (I kept mine as the master just for the documentation!) Should we still do the pull request or do you just want to use the active master moving forward? Thanks!
- Joe

**Comment by bsipocz** [comment]
Well, I would have rather saw this being merged as the repo was empty when I opened it. We could have been more coordinated :)

In general for any collaborative work I've always found working with PRs has more advantage than just pushing changes to master as 1) evetyone involved notices that something is happening 2) there isn't any bad surprises coming up of merge conflicts.

**Comment by hover2pi** [comment]
Absolutely. Sorry about that!

**Comment by jradavenport** [comment]
Yeah, this is totally on me. You submitted this PR during the first few hours of the hack day, and I was booting up this project as well as the gender survey analysis project, so I didn't see it until a few hours later.

Let us move towards the more traditional PR model now to ensure everybody gets to participate properly

**Comment by bsipocz** [comment]
@jradavenport @hover2pi - Tomorrow I can sort out the matching here, too (based on the three FFIs I have), so you can check which way to go.

**Comment by jradavenport** [comment]
My git skills are like a 3-leggd dog running the Iditarod

I think I was able to make github happy, and merged this from @bsipocz. Now we should all have both versions in our repo's (do a pull) and whomever gets the matching done will be the code we move forward with.

ALSO - as @bsipocz aptly points out, we should use the PR workflow. Thus I have removed @hover2pi from the "collaborators" list, so now only I can merge stuff. I hope this works!

**Pull request merged**
